[tox]
envlist =
    {py39,py310,py311,py312,py313,py314}-{c,pure},
    {pypy,pypy3}-pure,
    py313-x86,
isolated_build = true

[testenv]
deps=
    pytest

changedir=test
commands=
    c,x86: python -c 'from tmsgpack import _ctmsgpack'
    c,x86: py.test
    pure: py.test
setenv=
    pure: TMSGPACK_PUREPYTHON=x

[testenv:py313-x86]
basepython=python3.13-x86
deps=
    pytest

changedir=test
commands=
    python -c 'import sys; print(hex(sys.maxsize))'
    python -c 'from tmsgpack import _ctmsgpack'
    py.test
