name: Publish to PyPI and NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release  # Only needed if you set this up in PyPI

    permissions:
      id-token: write  # Required for PyPI and NPM trusted publishing
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Build Python package
      run: |
        cd Python
        python -m pip install build --sdist
        rm -rf dist/
        python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: Python/dist/

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Publish to NPM
      run: npm publish --provenance
      working-directory: ./JavaScript
